name: Build Ex QA Base

on:
  workflow_dispatch:
    inputs:
      testname:
        description: "Manual build"
        required: true
        default: ${TEST_NAME}
        type: string

permissions:
  contents: write
  issues: write


jobs:
  build:
    name: Build and Test Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download Artifacts from S3
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://maven.egeiper/org/egeiper/QA-Base/1.1.1/QA-Base-1.1.1.jar
          destination: ./target/libs
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1

      - name: Check files2
        run: find ~/ -type f -name "QA-Base-1.1.1.jar"
      - name: Check files3
        run: find "$(cd ..; pwd)" -name "QA-Base-1.1.1.jar"
        
