name: Run Tests with Gradle

on:
  workflow_dispatch:
    inputs:
      test_name:
        description: "Give specific test name or leave empty"
        required: true
        default: "\"tests*\""
        type: string

      qa_base_version:
        description: "QA-Base version to fetch from S3"
        required: true
        default: "1.1.3"
        type: string

permissions:
  contents: write
  issues: write


jobs:

  build:
    name: Build and Test Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'


      - name: Download Artifacts from S3
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://maven.egeiper/org/egeiper/QA-Base/${{ github.event.inputs.qa_base_version }}/QA-Base-${{ github.event.inputs.qa_base_version }}.jar
          destination: ./
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1

      - name: Start Selenium Hub and Nodes
        run: docker compose --env-file .arm64.env -f docker-compose.withoutTests.yml up -d

      - name: Check if hub and node is ready
        run: sh ./shFiles/healthcheckWithoutExecution.sh

      - name: Build and Test with Gradle
        id: tests_run
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean test -Pactions --tests ${{ github.event.inputs.test_name }}
        continue-on-error: true

      - name: Check on failures
        if: steps.tests_run.outcome != 'success'
        run: exit 1

      - name: Close Selenium Hub and Nodes
        run: docker compose -f docker-compose.withoutTests.yml down
        
        
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
