name: Run with Gradle
env:
  TEST_NAME: "tests*"
on:
  workflow_dispatch:
    inputs:
      testname:
        description: "Manual build"
        required: true
        default: ${TEST_NAME}
        type: string

permissions:
  contents: write
  issues: write


jobs:

  build:
    name: Build and Test Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'


      - name: Download Artifacts from S3
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://maven.egeiper/org/egeiper/QA-Base/1.1.1/QA-Base-1.1.1.jar
          destination: ./
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1

      - name: Start Selenium Hub and Nodes
        run: docker compose -f docker-compose.withoutTests.yml up -d

      - name: Check if hub and node is ready
        run: sh ./shFiles/healthcheckWithoutExecution.sh

      - name: Build and Test with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean test -Pactions --tests ${{ github.event.inputs.testname }}

      - name: Close Selenium Hub and Nodes
        run: docker compose -f docker-compose.withoutTests.yml down

  allure:
    name: Generate Allure Report
    if: always()
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: master
          path: master

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        #id: allure-report
        with:
          allure_results: allure-results
          #gh_pages: gh-pages
          #allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
